stages:

* build
* deploy

build:
stage: build
tags:
- Finsight-runner
script:
- npm ci
- npx ng build
artifacts:
paths:
- dist/

deploy:
stage: deploy
tags:
- Finsight-runner
only:
- main
script:
- docker build -t finsight-frontend .
- docker stop finsight-frontend || true
- docker rm finsight-frontend || true
- docker run -d --name finsight-frontend -p 80:80 finsight-frontend
