stages:
  - build
  - deploy

build:
  stage: build
  tags:
    - gitlab-runner
  script:
    - npm install
    - ng build
    - find dist -maxdepth 4 -type f
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  tags:
    - gitlab-runner
  script:
    - docker build -t finsight-frontend .
    - docker stop finsight-frontend || true
    - docker rm finsight-frontend || true
    - docker run -d --name finsight-frontend -p 80:80 finsight-frontend
    - docker exec finsight-frontend ls -la /usr/share/nginx/html
  only:
    - main

